### PR TITLE
Understanding Get-ACL and AD Drive Output

### PR DESCRIPTION
**Pull request by farismalaeb**
# PR Summary

## PR Checklist

- Do you want this post to be published on a specific date?: Y/N [Specify date]:
- [X] I have read the [contributors guide][contrib] and followed the style and process guidelines
- [ x] PR has a meaningful title
- [X ] Includes content related an open issue
  - see [Closing issues using keywords][key].
- [X ] This PR is ready to merge and is not **Work in Progress**

[contrib]: https://docs.microsoft.com/powershell/scripting/community/contributing/overview
[key]: https://help.github.com/en/articles/closing-issues-using-keywords

### CODE REVIEW

**Comment by doctordns** [comment]
It;'s probably me, but the commits noted above look like updates to the earlier post?

**Comment by farismalaeb** [comment]
Oh, sorry, should I do it again 
I can see also the ACL post is there

**Comment by doctordns** [comment]
> Oh, sorry, should I do it again
> I can see also the ACL post is there

Please?

**Comment by farismalaeb** [comment]
Will do another PR for this post

**Pull request closed without merging**
