### PR TITLE
Porting-GeneratePassword-From-C#

### PR DESCRIPTION
**Pull request by FranciscoNabas**
# PR Summary
Porting GeneratePassword From C# post.

## PR Checklist

- Do you want this post to be published on a specific date?: Y/N [Specify date]: N
- [X] I have read the [contributors guide][contrib] and followed the style and process guidelines
- [X] PR has a meaningful title
- [X] Includes content related an open issue
  - see [Closing issues using keywords][key].
- [X] This PR is ready to merge and is not **Work in Progress**

[contrib]: https://docs.microsoft.com/powershell/scripting/community/contributing/overview
[key]: https://help.github.com/en/articles/closing-issues-using-keywords

### CODE REVIEW

**Review by sdwheeler — CHANGES_REQUESTED** [review]
@FranciscoNabas Thanks for the post. There are several formatting issues with this post, but the biggest issue is that the code doesn't work. There is an unbalance brace or a line of code out of place in `Get-IsDangerousString`.

For the other formatting, please use backticks for cmdlet names, variables, and user input when referenced in a paragraph. Also, there are 2 extra spaces at the end of the lines, which cause markdown to not flow correctly. It would be easier to review if you limited the lines 100 characters, per our style guide. You can use the [Reflow Markdown](https://marketplace.visualstudio.com/items?itemName=marvhen.reflow-markdown) extension in VS Code.

**Comment by FranciscoNabas** [comment]
Hi! Thanks for the feedback, it has been some time since my last post, I'm a little rusty. I'm working on the fixes.

**Comment by sdwheeler** [comment]
> Hi! Thanks for the feedback, it has been some time since my last post, I'm a little rusty. I'm working on the fixes.

Also, can you do this work in a working branch instead of `main`?

**Comment by FranciscoNabas** [comment]
Sure thing, will do.

**Pull request closed without merging**
