### PR TITLE
Update on post

### PR DESCRIPTION
**Pull request by FranciscoNabas**
# PR Summary
New Blog Post - Monitor Folder With File Watcher

## PR Checklist

- Do you want this post to be published on a specific date?: Y/N [Specify date]:
- [x] I have read the [contributors guide][contrib] and followed the style and process guidelines
- [x] PR has a meaningful title
- [x] Includes content related an open issue
  - see [Closing issues using keywords][key].
- [x] This PR is ready to merge and is not **Work in Progress**

[contrib]: https://docs.microsoft.com/powershell/scripting/community/contributing/overview
[key]: https://help.github.com/en/articles/closing-issues-using-keywords

### CODE REVIEW

**Comment by doctordns** [comment]
I will do a line by line review later. Some general comments.
* a lot of typos (i instead of I,for example). Please run your text through a spell checker.  Use VSCode with the MD ans spell checking extensions.

**Comment by doctordns** [comment]
Closed in error.

**Comment by FranciscoNabas** [comment]
Thank you very much for your feedback. I will follow your recommendations.

**Comment by doctordns** [comment]
> Thank you very much for your feedback. I will follow your recommendations.

Excellent. I look forward to the update.

I try to ensure that all the posts here are well written using decent Technical American English to try to ensure the posts are as readable as possible for the widest possible audience. So please do not take my comments personally. You should see the reviews Mr Wheeler gives my posts!

**Comment by FranciscoNabas** [comment]
Not took it personally at all. This is my first interaction with this blog and any suggestion is welcome. Also I am aware that my grammar is not the best. Is not my first language and I'm looking forward to improve it. Thanks!

**Comment by doctordns** [comment]
Any progress?

**Comment by doctordns** [comment]
Are you planning on updating this?

**Comment by FranciscoNabas** [comment]
My apologies on the response delay. A couple of factors kept me from getting back to this.
I will review the post following the recommendations.
I want to be experienced on this, I have many ideas to share.
Thank you very much for your patience.

**Comment by doctordns** [comment]
Thanks for your reply.

Sadly, there is another blog post being finalised that your proposed post would conflict with. Thus we cannot accept _this_ post. 

Please consider finding a different topic and submitting another article - happy to help you succeed!

**Comment by FranciscoNabas** [comment]
No worries at all, thank you for letting me know. will proceed with other topics.
Thanks!

**Comment by doctordns** [comment]
Since this would be, in effect, a post which duplicates another one that is almost complete, we have to reject this.,

I hope the OP can find another topic on which to write. I look forward to working to make that happen.

**Pull request closed without merging**
